In [1]:
# Cálculo de riesgo empírico que corresponde a un función de pérdida
import numpy as np
import pandas as pd

In [2]:
# Datos tabla 1
x = np.array([-2, -1, 0, 1, 2])
y = np.array([3, 2, 1, 1, 0.5])

In [3]:
# Funciones de pérdida
f1 = 1.5 - 0.6 * x
f2 = 1.5 - 0.5 * x

# Pérdida cuadrática
loss_quad_f1 = (y - f1) ** 2
loss_quad_f2 = (y - f2) ** 2

# Pérdida absoluta
loss_abs_f1 = np.abs(y - f1)
loss_abs_f2 = np.abs(y - f2)

# Funciones
f1 = 1.5 - 0.6 * x
f2 = 1.5 - 0.5 * x

In [4]:
# Riesgos empíricos
print("Riesgo empírico")
print("Pérdida cuadrática:")
print(f"Función 1: {loss_quad_f1.mean():.4f}")
print(f"Función 2: {loss_quad_f2.mean():.4f}")

print("\nPérdida absoluta:")
print(f"Función 1: {loss_abs_f1.mean():.4f}")
print(f"Función 2: {loss_abs_f2.mean():.4f}")

Riesgo empírico
Pérdida cuadrática:
Función 1: 0.0800
Función 2: 0.1000

Pérdida absoluta:
Función 1: 0.2400
Función 2: 0.2000

In [7]:
df = pd.read_csv(r'C:\Users\Usuario\Downloads\Classified_Data.csv')

In [8]:
df

,Unnamed: 0,WTT,PTI,EQW,SBI,LQE,QWG,FDJ,PJF,HQE,NXJ,TARGET CLASS
0,0,0.913917,1.162073,0.567946,0.755464,0.780862,0.352608,0.759697,0.643798,0.879422,1.231409,1
1,1,0.635632,1.003722,0.535342,0.825645,0.924109,0.648450,0.675334,1.013546,0.621552,1.492702,0
2,2,0.721360,1.201493,0.921990,0.855595,1.526629,0.720781,1.626351,1.154483,0.957877,1.285597,0
3,3,1.234204,1.386726,0.653046,0.825624,1.142504,0.875128,1.409708,1.380003,1.522692,1.153093,1
4,4,1.279491,0.949750,0.627280,0.668976,1.232537,0.703727,1.115596,0.646691,1.463812,1.419167,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,1.010953,1.034006,0.853116,0.622460,1.036610,0.586240,0.746811,0.319752,1.117340,1.348517,1
996,996,0.575529,0.955786,0.941835,0.792882,1.414277,1.269540,1.055928,0.713193,0.958684,1.663489,0
997,997,1.135470,0.982462,0.781905,0.916738,0.901031,0.884738,0.386802,0.389584,0.919191,1.385504,1
998,998,1.084894,0.861769,0.407158,0.665696,1.608612,0.943859,0.855806,1.061338,1.277456,1.188063,1
999,999,0.837460,0.961184,0.417006,0.799784,0.934399,0.424762,0.778234,0.907962,1.257190,1.364837,1

In [9]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [10]:
df.head()

,WTT,PTI,EQW,SBI,LQE,QWG,FDJ,PJF,HQE,NXJ,TARGET CLASS
0,0.913917,1.162073,0.567946,0.755464,0.780862,0.352608,0.759697,0.643798,0.879422,1.231409,1
1,0.635632,1.003722,0.535342,0.825645,0.924109,0.648450,0.675334,1.013546,0.621552,1.492702,0
2,0.721360,1.201493,0.921990,0.855595,1.526629,0.720781,1.626351,1.154483,0.957877,1.285597,0
3,1.234204,1.386726,0.653046,0.825624,1.142504,0.875128,1.409708,1.380003,1.522692,1.153093,1
4,1.279491,0.949750,0.627280,0.668976,1.232537,0.703727,1.115596,0.646691,1.463812,1.419167,1