### Ejemplo libro Geron para teoría

In [1]:
# Set working directory
import os
import pandas as pd

os.chdir("C:/Users/Usuario/Downloads")

#Parse dates identifica que se trata de fechas, lo cual vemos se hizo correctamente con df.info()
df = pd.read_csv("CTA_-_Ridership_-_Daily_Boarding_Totals.csv",parse_dates=["service_date"])
#Los datos son diarios
df

     service_date day_type     bus  rail_boardings  total_rides
0      2001-01-01        U  297192          126455       423647
1      2001-01-02        W  780827          501952      1282779
2      2001-01-03        W  824923          536432      1361355
3      2001-01-04        W  870021          550011      1420032
4      2001-01-05        W  890426          557917      1448343
...           ...      ...     ...             ...          ...
7696   2021-11-26        W  257700          189694       447394
7697   2021-11-27        A  237839          187065       424904
7698   2021-11-28        U  184817          147830       332647
7699   2021-11-29        W  421322          276090       697412
7700   2021-11-30        W  450230          302349       752579

[7701 rows x 5 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7701 entries, 0 to 7700
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    7701 non-null   datetime64[ns]
 1   day_type        7701 non-null   object
 2   bus             7701 non-null   int64
 3   rail_boardings  7701 non-null   int64
 4   total_rides     7701 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 300.9+ KB

In [2]:
#Cambiar el nombre de las columnas
df.columns = ["date", "day_type", "bus", "rail", "total"]  # shorter names
#Ordenar por fecha
df = df.sort_values("date").set_index("date")
#Quitar total que es la suma de dos columnas
df = df.drop("total", axis=1)  # no need for total, it's just bus + rail
df = df.drop_duplicates()  # remove duplicated months (2011-10 and 2014-07)

In [3]:
df.head()

           day_type     bus    rail
date
2001-01-01        U  297192  126455
2001-01-02        W  780827  501952
2001-01-03        W  824923  536432
2001-01-04        W  870021  550011
2001-01-05        W  890426  557917

In [4]:
#Vamos a estudiar solo la columna rail. Como preprocesamiento, dividimos entre 1e6. Tomamos como entrenamiento
#el 2016 al 2018, como validación desde enero hasta finales de mayo (medio año) y prueba el resto

rail_train = df["rail"]["2016-01":"2018-12"] / 1e6
rail_valid = df["rail"]["2019-01":"2019-05"] / 1e6
rail_test = df["rail"]["2019-06":] / 1e6

In [5]:
import tensorflow as tf

#A continuaci\'on tomamos ventanas de tama\~no 56 cuyos valores son los inputs para una vez desdoblada la red
#tomar el valor de las observaciones una unidad en el tiempo futuro como outputs, siendo nuestro output real el valor de 
#la observaci\'on en el tiempo 57. De esta forma, al desdoblar la red las observaciones en el output 
#tienen el mismo tama\~o que la ventana para que haya contra quien asociar cada valor del input.
#Luego, tomamos un tama\~o de batch de 32 (se divide la muestra de miniseries en 32) aleatoriamente con una semilla
#de 42 para reproducibilidad.

#Tomamos un tamaño de batch de 32 y se revuelve con una semilla de 42. En cada batch vamos a tener muestras
#de las observaciones en el conjunto de entrenamiento, lo cual se refleja en que se tienen muestras de las ventanas. 

seq_length = 56
tf.random.set_seed(42)  # extra code – ensures reproducibility
train_ds = tf.keras.utils.timeseries_dataset_from_array(
    rail_train.to_numpy(),
    targets=rail_train[seq_length:],
    sequence_length=seq_length,
    batch_size=32,
    shuffle=True,
    seed=42
)

#Se utilizar\'a el modelo aprendido sobre los datos de validaci\'on, prediciendo a partir de 56 observaciones,
#el tama\~no de las ventana, la siguiente observaci\'on. Se incuye el tamaño del batch, 32, porque en la estimaci\'on
#final de cada observaci\'on hay que promediar las predicciones que se obtengan con los 32 distintos modelos aprendidos
valid_ds = tf.keras.utils.timeseries_dataset_from_array(
    rail_valid.to_numpy(),
    targets=rail_valid[seq_length:],
    sequence_length=seq_length,
    batch_size=32
)

In [7]:
#Agregar una neurona recurrente simple, o sea es una arquitectura en la cual tenemos un delay que corresponde a una
#capa oculta, los inputs están dadas por los valores de las ventanas y los outputs son los valores sobre los que se predice

tf.random.set_seed(42)  # extra code – ensures reproducibility
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(1, input_shape=[None, 1])
])

C:\Users\Usuario\anaconda3\lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [8]:
# extra code – defines a utility function we'll reuse several time

def fit_and_evaluate(model, train_set, valid_set, learning_rate, epochs=500):
    early_stopping_cb = tf.keras.callbacks.EarlyStopping(
        monitor="val_mae", patience=50, restore_best_weights=True)
    opt = tf.keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.9)
    model.compile(loss=tf.keras.losses.Huber(), optimizer=opt, metrics=["mae"])
    history = model.fit(train_set, validation_data=valid_set, epochs=epochs,
                        callbacks=[early_stopping_cb])
    valid_loss, valid_mae = model.evaluate(valid_set)
    return valid_mae * 1e6

In [9]:
##Ajuste 

fit_and_evaluate(model, train_ds, valid_ds, learning_rate=0.02)

Epoch 1/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0618 - mae: 0.3113 - val_loss: 0.0120 - val_mae: 0.1162
Epoch 2/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0122 - mae: 0.1236 - val_loss: 0.0120 - val_mae: 0.1157
Epoch 3/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0116 - mae: 0.1236 - val_loss: 0.0115 - val_mae: 0.1170
Epoch 4/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0116 - mae: 0.1262 - val_loss: 0.0115 - val_mae: 0.1164
Epoch 5/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0117 - mae: 0.1272 - val_loss: 0.0115 - val_mae: 0.1164
Epoch 6/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0114 - mae: 0.1247 - val_loss: 0.0114 - val_mae: 0.1164
Epoch 7/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0114 - mae: 0.1255 - val_loss: 0.0114 - val_mae: 0.1159
Epoch 8/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0110 - mae: 0.1224 - val_loss: 0.0113 - val_mae: 0.1158
Epoch 9/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0111 - mae: 0.1238 - val_loss: 0.0113 - val_mae: 0.1155
Epoch 10/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0111 - mae: 0.1234 - val_loss: 0.0113 - val_mae: 0.1151
Epoch 11/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0115 - mae: 0.1251 - val_loss: 0.0112 - val_mae: 0.1150
Epoch 12/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0108 - mae: 0.1215 - val_loss: 0.0111 - val_mae: 0.1149
Epoch 13/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0114 - mae: 0.1251 - val_loss: 0.0111 - val_mae: 0.1144
Epoch 14/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0107 - mae: 0.1208 - val_loss: 0.0111 - val_mae: 0.1142
Epoch 15/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0104 - mae: 0.1196 - val_loss: 0.0110 - val_mae: 0.1144
Epoch 16/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0113 - mae: 0.1248 - val_loss: 0.0109 - val_mae: 0.1139
Epoch 17/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0111 - mae: 0.1223 - val_loss: 0.0109 - val_mae: 0.1133
Epoch 18/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0109 - mae: 0.1224 - val_loss: 0.0108 - val_mae: 0.1135
Epoch 19/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0108 - mae: 0.1208 - val_loss: 0.0109 - val_mae: 0.1128
Epoch 20/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1175 - val_loss: 0.0108 - val_mae: 0.1125
Epoch 21/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0112 - mae: 0.1234 - val_loss: 0.0107 - val_mae: 0.1125
Epoch 22/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0110 - mae: 0.1214 - val_loss: 0.0107 - val_mae: 0.1119
Epoch 23/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1198 - val_loss: 0.0107 - val_mae: 0.1117
Epoch 24/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0108 - mae: 0.1209 - val_loss: 0.0107 - val_mae: 0.1114
Epoch 25/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1200 - val_loss: 0.0107 - val_mae: 0.1110
Epoch 26/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1196 - val_loss: 0.0106 - val_mae: 0.1108
Epoch 27/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1187 - val_loss: 0.0106 - val_mae: 0.1103
Epoch 28/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0107 - mae: 0.1193 - val_loss: 0.0106 - val_mae: 0.1101
Epoch 29/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1185 - val_loss: 0.0106 - val_mae: 0.1097
Epoch 30/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1205 - val_loss: 0.0105 - val_mae: 0.1094
Epoch 31/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1173 - val_loss: 0.0105 - val_mae: 0.1090
Epoch 32/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0108 - mae: 0.1194 - val_loss: 0.0105 - val_mae: 0.1088
Epoch 33/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0111 - mae: 0.1215 - val_loss: 0.0105 - val_mae: 0.1084
Epoch 34/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0112 - mae: 0.1201 - val_loss: 0.0104 - val_mae: 0.1083
Epoch 35/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0110 - mae: 0.1202 - val_loss: 0.0104 - val_mae: 0.1080
Epoch 36/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1182 - val_loss: 0.0104 - val_mae: 0.1078
Epoch 37/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1154 - val_loss: 0.0104 - val_mae: 0.1075
Epoch 38/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1164 - val_loss: 0.0104 - val_mae: 0.1073
Epoch 39/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1171 - val_loss: 0.0104 - val_mae: 0.1070
Epoch 40/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1142 - val_loss: 0.0104 - val_mae: 0.1069
Epoch 41/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1147 - val_loss: 0.0104 - val_mae: 0.1067
Epoch 42/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1167 - val_loss: 0.0103 - val_mae: 0.1066
Epoch 43/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0108 - mae: 0.1178 - val_loss: 0.0103 - val_mae: 0.1064
Epoch 44/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1147 - val_loss: 0.0103 - val_mae: 0.1062
Epoch 45/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0111 - mae: 0.1186 - val_loss: 0.0103 - val_mae: 0.1059
Epoch 46/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1148 - val_loss: 0.0103 - val_mae: 0.1058
Epoch 47/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0101 - mae: 0.1141 - val_loss: 0.0103 - val_mae: 0.1057
Epoch 48/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0108 - mae: 0.1175 - val_loss: 0.0103 - val_mae: 0.1055
Epoch 49/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1157 - val_loss: 0.0103 - val_mae: 0.1054
Epoch 50/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1152 - val_loss: 0.0103 - val_mae: 0.1052
Epoch 51/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1140 - val_loss: 0.0103 - val_mae: 0.1051
Epoch 52/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1153 - val_loss: 0.0103 - val_mae: 0.1051
Epoch 53/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1162 - val_loss: 0.0103 - val_mae: 0.1049
Epoch 54/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0108 - mae: 0.1169 - val_loss: 0.0103 - val_mae: 0.1048
Epoch 55/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0112 - mae: 0.1197 - val_loss: 0.0103 - val_mae: 0.1046
Epoch 56/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0101 - mae: 0.1126 - val_loss: 0.0103 - val_mae: 0.1046
Epoch 57/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0098 - mae: 0.1103 - val_loss: 0.0103 - val_mae: 0.1045
Epoch 58/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1137 - val_loss: 0.0103 - val_mae: 0.1045
Epoch 59/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1143 - val_loss: 0.0103 - val_mae: 0.1043
Epoch 60/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1118 - val_loss: 0.0103 - val_mae: 0.1042
Epoch 61/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1145 - val_loss: 0.0103 - val_mae: 0.1042
Epoch 62/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1141 - val_loss: 0.0103 - val_mae: 0.1040
Epoch 63/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1146 - val_loss: 0.0103 - val_mae: 0.1040
Epoch 64/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1140 - val_loss: 0.0103 - val_mae: 0.1040
Epoch 65/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1140 - val_loss: 0.0103 - val_mae: 0.1038
Epoch 66/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0108 - mae: 0.1161 - val_loss: 0.0103 - val_mae: 0.1038
Epoch 67/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0108 - mae: 0.1151 - val_loss: 0.0103 - val_mae: 0.1038
Epoch 68/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0103 - mae: 0.1127 - val_loss: 0.0103 - val_mae: 0.1037
Epoch 69/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0108 - mae: 0.1164 - val_loss: 0.0102 - val_mae: 0.1037
Epoch 70/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0101 - mae: 0.1113 - val_loss: 0.0103 - val_mae: 0.1036
Epoch 71/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0106 - mae: 0.1145 - val_loss: 0.0103 - val_mae: 0.1036
Epoch 72/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0104 - mae: 0.1145 - val_loss: 0.0103 - val_mae: 0.1035
Epoch 73/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1127 - val_loss: 0.0103 - val_mae: 0.1034
Epoch 74/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1145 - val_loss: 0.0103 - val_mae: 0.1034
Epoch 75/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1134 - val_loss: 0.0103 - val_mae: 0.1034
Epoch 76/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0108 - mae: 0.1152 - val_loss: 0.0102 - val_mae: 0.1034
Epoch 77/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1148 - val_loss: 0.0103 - val_mae: 0.1033
Epoch 78/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1139 - val_loss: 0.0103 - val_mae: 0.1033
Epoch 79/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1131 - val_loss: 0.0102 - val_mae: 0.1033
Epoch 80/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1165 - val_loss: 0.0102 - val_mae: 0.1033
Epoch 81/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1138 - val_loss: 0.0103 - val_mae: 0.1032
Epoch 82/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1136 - val_loss: 0.0103 - val_mae: 0.1032
Epoch 83/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0111 - mae: 0.1174 - val_loss: 0.0102 - val_mae: 0.1032
Epoch 84/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1124 - val_loss: 0.0103 - val_mae: 0.1032
Epoch 85/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1134 - val_loss: 0.0103 - val_mae: 0.1032
Epoch 86/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1141 - val_loss: 0.0103 - val_mae: 0.1031
Epoch 87/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0108 - mae: 0.1155 - val_loss: 0.0103 - val_mae: 0.1031
Epoch 88/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0100 - mae: 0.1114 - val_loss: 0.0103 - val_mae: 0.1031
Epoch 89/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0098 - mae: 0.1099 - val_loss: 0.0103 - val_mae: 0.1031
Epoch 90/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1119 - val_loss: 0.0102 - val_mae: 0.1032
Epoch 91/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0100 - mae: 0.1109 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 92/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1148 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 93/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1130 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 94/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0112 - mae: 0.1181 - val_loss: 0.0103 - val_mae: 0.1031
Epoch 95/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0108 - mae: 0.1145 - val_loss: 0.0102 - val_mae: 0.1032
Epoch 96/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0102 - mae: 0.1115 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 97/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0109 - mae: 0.1163 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 98/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1120 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 99/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1133 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 100/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1126 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 101/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1125 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 102/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1140 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 103/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0106 - mae: 0.1139 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 104/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0109 - mae: 0.1159 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 105/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0101 - mae: 0.1119 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 106/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0102 - mae: 0.1118 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 107/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0111 - mae: 0.1182 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 108/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0099 - mae: 0.1102 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 109/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1129 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 110/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0106 - mae: 0.1141 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 111/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1145 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 112/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1128 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 113/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1141 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 114/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1127 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 115/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1138 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 116/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1136 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 117/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0100 - mae: 0.1113 - val_loss: 0.0102 - val_mae: 0.1031
Epoch 118/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0101 - mae: 0.1117 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 119/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1148 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 120/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1129 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 121/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0102 - mae: 0.1124 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 122/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1129 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 123/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1133 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 124/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0104 - mae: 0.1128 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 125/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0102 - mae: 0.1121 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 126/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1132 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 127/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0095 - mae: 0.1074 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 128/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1134 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 129/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1137 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 130/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1127 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 131/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1130 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 132/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1131 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 133/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0105 - mae: 0.1138 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 134/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0106 - mae: 0.1150 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 135/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1133 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 136/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1140 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 137/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1128 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 138/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0098 - mae: 0.1098 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 139/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1131 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 140/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0107 - mae: 0.1151 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 141/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0099 - mae: 0.1101 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 142/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0101 - mae: 0.1117 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 143/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1126 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 144/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0108 - mae: 0.1165 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 145/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0112 - mae: 0.1172 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 146/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1129 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 147/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0106 - mae: 0.1140 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 148/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0100 - mae: 0.1111 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 149/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1119 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 150/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1125 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 151/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0106 - mae: 0.1149 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 152/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0101 - mae: 0.1111 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 153/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0101 - mae: 0.1110 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 154/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0101 - mae: 0.1114 - val_loss: 0.0102 - val_mae: 0.1029
Epoch 155/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0107 - mae: 0.1148 - val_loss: 0.0103 - val_mae: 0.1028
Epoch 156/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0101 - mae: 0.1111 - val_loss: 0.0103 - val_mae: 0.1028
Epoch 157/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0104 - mae: 0.1139 - val_loss: 0.0103 - val_mae: 0.1028
Epoch 158/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0106 - mae: 0.1150 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 159/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1144 - val_loss: 0.0103 - val_mae: 0.1028
Epoch 160/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.1141 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 161/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0097 - mae: 0.1092 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 162/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0106 - mae: 0.1143 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 163/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1143 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 164/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.1125 - val_loss: 0.0103 - val_mae: 0.1030
Epoch 165/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0105 - mae: 0.1139 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 166/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.1138 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 167/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.1128 - val_loss: 0.0103 - val_mae: 0.1029
Epoch 168/500
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0103 - mae: 0.1121 - val_loss: 0.0102 - val_mae: 0.1030
Epoch 169/500

102779.90996837616